<?php
/**
 * Custom error/maintenance page
 * 
 * @category  Steverobbins
 * @package   Steverobbins_Staticversion
 * @author    Steve Robbins <steven.j.robbins@gmail.com>
 * @copyright Copyright (c) 2014 Steve Robbins (https://github.com/steverobbins)
 * @license   http://creativecommons.org/licenses/by/3.0/deed.en_US Creative Commons Attribution 3.0 Unported License
 */
?>
<h1>404 error: Page not found.</h1>