<?php
/**
 * Custom error/maintenance page
 * 
 * @category  Steverobbins
 * @package   Steverobbins_Errorpage
 * @author    Steve Robbins <steven.j.robbins@gmail.com>
 * @copyright Copyright (c) 2014 Steve Robbins (https://github.com/steverobbins)
 * @license   http://creativecommons.org/licenses/by/3.0/deed.en_US Creative Commons Attribution 3.0 Unported License
 */
?>
<div style="text-align:center">
    <h1>Down for Maintenance</h1>
    <p>We'll be back shortly!</p>
</div>